obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
#robot_radius: ir_of_robot
footprint: [ [0.65, 0.6], [0.65, -0.6], [-0.65, -0.6], [-0.65, 0.6]]
inflation_radius: 3.0

observation_sources: laser_scan_sensor 

# marking - add obstacle information to cost map
# clearing - clear obstacle information to cost map
laser_scan_sensor: {sensor_frame: front_lidar, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

