
# Publish joint states
general_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 25

# Diff drive controller 
general_velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['front_left_wheel_joint', 'rear_left_wheel_joint']
  right_wheel: ['front_right_wheel_joint', 'rear_right_wheel_joint']
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  cmd_vel_timeout: 0.5
  velocity_rolling_window_size: 2

  # # Wheelbase
  wheel_separation: 0.571
  wheel_radius: 0.178

  # Base frame_id
  base_frame_id: base_link

  # TF publisher
  enable_odom_tf: true
  odom_frame_id: odom

  # hardware provides estimate
  estimate_velocity_from_position: false

  # Multiplier for calibration
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity and acceleration limits
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.5   # m/s
      has_acceleration_limits: true
      max_acceleration       : 3.5   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 2.5   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 6.5   # rad/s^2