<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="general">

    <xacro:include filename="$(find general_description)/config/$(arg robot_name)_config.urdf.xacro" />
    <xacro:include filename="$(find general_description)/urdf/material.urdf.xacro" />
    <xacro:include filename="$(find general_description)/urdf/inertia.urdf.xacro" />
    <xacro:include filename="$(find general_description)/urdf/chasis.urdf.xacro" />
    <xacro:include filename="$(find general_description)/urdf/wheel.urdf.xacro" />
    <xacro:include filename="$(find general_description)/urdf/sensor.urdf.xacro" />
    <xacro:include filename="$(find general_description)/urdf/gazebo.xacro" />

    <xacro:property name="z_pos_wheel" value="${-wheel_center_to_chasis_center + chasis_height/2}" />
    <xacro:property name="front_left_wheel_pos" value="${x_pos_wheel} ${y_pos_wheel} ${z_pos_wheel}" />
    <xacro:property name="front_right_wheel_pos" value="${x_pos_wheel} ${-y_pos_wheel} ${z_pos_wheel}" />
    <xacro:property name="rear_left_wheel_pos" value="${-x_pos_wheel} ${y_pos_wheel} ${z_pos_wheel}" />
    <xacro:property name="rear_right_wheel_pos" value="${-x_pos_wheel} -${y_pos_wheel} ${z_pos_wheel}" />

    <!-- Adding four wheels -->
    <xacro:wheel link_name="front_left_wheel" wheel_pos="${front_left_wheel_pos}" mesh_filename="${robot_name}/left_wheel.dae"/>
    <xacro:wheel link_name="front_right_wheel" wheel_pos="${front_right_wheel_pos}" mesh_filename="${robot_name}/right_wheel.dae"/>
    <xacro:wheel link_name="rear_left_wheel" wheel_pos="${rear_left_wheel_pos}" mesh_filename="${robot_name}/left_wheel.dae"/>
    <xacro:wheel link_name="rear_right_wheel" wheel_pos="${rear_right_wheel_pos}" mesh_filename="${robot_name}/right_wheel.dae"/>

    <!-- Adding sensors -->

    <!-- Lidar Sensor -->
    <xacro:if value="$(arg enable_lidar)">
        <xacro:sensor_lidar link_name="${lidar_link_name}" xyz="${x_pos_lidar} ${y_pos_lidar} ${z_pos_lidar + chasis_height/2}" rpy="${lidar_rpy}"/>
    </xacro:if>

    <!-- IMU Sensor -->
    <xacro:if value="$(arg enable_imu)">
        <xacro:sensor_imu link_name="${imu_link_name}" xyz="${x_pos_imu} ${y_pos_imu} ${z_pos_imu + chasis_height/2}" rpy="${imu_rpy}"/>
    </xacro:if>

    <!-- Stereo Camera Sensor -->
    <xacro:if value="$(arg enable_stereo)">
        <xacro:sensor_stereo link_name="${camera_link_name}" xyz="${x_pos_camera} ${y_pos_camera} ${z_pos_camera + chasis_height/2}" rpy="${camera_rpy}"/>
    </xacro:if>

    <!-- GPS Sensor -->
    <xacro:if value="$(arg enable_gps)">
        <xacro:sensor_gps link_name="${gps_link_name}" xyz="${x_pos_gps} ${y_pos_gps} ${y_pos_gps + chasis_height/2}" rpy="${gps_rpy}"/>
    </xacro:if>

</robot>