<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


    <!-- Robot Name -->
    <xacro:property name="robot_name" value="husky" />

    <!-- Chasis configuration -->
    <xacro:property name="chasis_mass" value="5" />
    <xacro:property name="chasis_length" value="0.985" />
    <xacro:property name="chasis_width" value="0.571" />
    <xacro:property name="chasis_height" value="0.249" />
    <xacro:property name="chasis_meshfile" value="${robot_name}/chasis.dae" />

    <!-- Wheel configuration -->
    <!-- Absolute value of distance of wheel center from the center of the chasis -->
    <xacro:property name="wheel_center_to_chasis_center" value="0.092" />
    <xacro:property name="wheel_mass" value="2" />
    <xacro:property name="wheel_radius" value="0.178" />
    <xacro:property name="wheel_thickness" value="0.114" />
    <xacro:property name="left_wheel_meshfile" value="${robot_name}/wheel.dae" />
    <xacro:property name="right_wheel_meshfile" value="${robot_name}/wheel.dae" />

    <!-- Add the height of the wheel wrt to center of the chasis instead of the numeric value -->
    <xacro:property name="z_pos_wheel" value="${-wheel_center_to_chasis_center + chasis_height/2}" />
    <xacro:property name="x_pos_wheel" value="0.256" />
    <xacro:property name="y_pos_wheel" value="0.2854" />
    <xacro:property name="front_left_wheel_pos" value="${x_pos_wheel} ${y_pos_wheel} ${z_pos_wheel}" />
    <xacro:property name="front_right_wheel_pos" value="${x_pos_wheel} ${-y_pos_wheel} ${z_pos_wheel}" />
    <xacro:property name="rear_left_wheel_pos" value="${-x_pos_wheel} ${y_pos_wheel} ${z_pos_wheel}" />
    <xacro:property name="rear_right_wheel_pos" value="${-x_pos_wheel} -${y_pos_wheel} ${z_pos_wheel}" />

</robot>