<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Robot Name -->
    <xacro:property name="robot_name" value="pioneer3at" />

    <!-- Chasis configuration -->
    <xacro:property name="chasis_mass" value="5" />
    <xacro:property name="chasis_length" value="0.508" />
    <xacro:property name="chasis_width" value="0.383" />
    <xacro:property name="chasis_height" value="0.195" />
    <xacro:property name="chasis_meshfile" value="${robot_name}/chasis.dae" />

    <!-- Wheel configuration -->
    <xacro:property name="wheel_mass" value="2" />
    <xacro:property name="wheel_radius" value="0.111" />
    <xacro:property name="wheel_thickness" value="0.096" />
    <xacro:property name="left_wheel_meshfile" value="${robot_name}/left_wheel.dae" />
    <xacro:property name="right_wheel_meshfile" value="${robot_name}/right_wheel.dae" />

    <!-- Absolute value of height of wheel center from the center of the chasis -->
    <xacro:property name="wheel_center_to_chasis_center" value="0.066" />
    <xacro:property name="z_pos_wheel" value="${-wheel_center_to_chasis_center + chasis_height/2}" />
    <xacro:property name="x_pos_wheel" value="0.134" />
    <xacro:property name="y_pos_wheel" value="0.199" />
    <xacro:property name="front_left_wheel_pos" value="${x_pos_wheel} ${y_pos_wheel} ${z_pos_wheel}" />
    <xacro:property name="front_right_wheel_pos" value="${x_pos_wheel} ${-y_pos_wheel} ${z_pos_wheel}" />
    <xacro:property name="rear_left_wheel_pos" value="${-x_pos_wheel} ${y_pos_wheel} ${z_pos_wheel}" />
    <xacro:property name="rear_right_wheel_pos" value="${-x_pos_wheel} -${y_pos_wheel} ${z_pos_wheel}" />

</robot>